name = "XrayAttenuation"
uuid = "7811750c-a499-436e-8b04-55fc0593dd37"
authors = ["Dale Black"]
version = "0.2.3"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AxisArrays = "0.4"
Interpolations = "0.15, 0.16"
Unitful = "1"
julia = "1.10 - 1.12"

[extras]
Attenuations = "0ff343a0-c53e-11e9-1400-85e187be3184"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Attenuations"]
